-- MySQL Script generated by MySQL Workbench
-- vie 08 jul 2022 21:35:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Portfolio` ;
USE `Portfolio` ;

-- -----------------------------------------------------
-- Table `Portfolio`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`PERSONA` (
  `id` INT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `perfil` VARCHAR(255) NOT NULL,
  `trabajo_actual` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`EXPERIENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`EXPERIENCIA` (
  `id` INT NOT NULL,
  `puesto` VARCHAR(255) NOT NULL,
  `empresa` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `logo` BLOB NULL,
  `PERSONA_id` INT NOT NULL,
  PRIMARY KEY (`id`, `PERSONA_id`),
  INDEX `fk_EXPERIENCIA_PERSONA_idx` (`PERSONA_id` ASC) VISIBLE,
  CONSTRAINT `fk_EXPERIENCIA_PERSONA`
    FOREIGN KEY (`PERSONA_id`)
    REFERENCES `Portfolio`.`PERSONA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`EDUCACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`EDUCACION` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `institucion` VARCHAR(255) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `logo` BLOB NULL,
  `PERSONA_id` INT NOT NULL,
  PRIMARY KEY (`id`, `PERSONA_id`),
  INDEX `fk_EDUCACION_PERSONA1_idx` (`PERSONA_id` ASC) VISIBLE,
  CONSTRAINT `fk_EDUCACION_PERSONA1`
    FOREIGN KEY (`PERSONA_id`)
    REFERENCES `Portfolio`.`PERSONA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`CURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`CURSO` (
  `id` INT NOT NULL,
  `nombre_curso` VARCHAR(255) NOT NULL,
  `institucion` VARCHAR(255) NOT NULL,
  `carga_horaria` VARCHAR(45) NULL,
  `periodo` DATE NOT NULL,
  `logo` BLOB NULL,
  `PERSONA_id` INT NOT NULL,
  PRIMARY KEY (`id`, `PERSONA_id`),
  INDEX `fk_CURSO_PERSONA1_idx` (`PERSONA_id` ASC) VISIBLE,
  CONSTRAINT `fk_CURSO_PERSONA1`
    FOREIGN KEY (`PERSONA_id`)
    REFERENCES `Portfolio`.`PERSONA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`HABILIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`HABILIDAD` (
  `id` INT NOT NULL,
  `nombre_habilidad` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  `PERSONA_id` INT NOT NULL,
  PRIMARY KEY (`id`, `PERSONA_id`),
  INDEX `fk_HABILIDAD_PERSONA1_idx` (`PERSONA_id` ASC) VISIBLE,
  CONSTRAINT `fk_HABILIDAD_PERSONA1`
    FOREIGN KEY (`PERSONA_id`)
    REFERENCES `Portfolio`.`PERSONA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`PROYECTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`PROYECTO` (
  `id` INT NOT NULL,
  `nombre_proyecto` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `url` VARCHAR(45) NULL,
  `img` BLOB NULL,
  `PERSONA_id` INT NOT NULL,
  PRIMARY KEY (`id`, `PERSONA_id`),
  INDEX `fk_PROYECTO_PERSONA1_idx` (`PERSONA_id` ASC) VISIBLE,
  CONSTRAINT `fk_PROYECTO_PERSONA1`
    FOREIGN KEY (`PERSONA_id`)
    REFERENCES `Portfolio`.`PERSONA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
