---

application:
  audience: https://portfolio-backend-prueba.herokuapp.com/
  client-origin-url: https://portfolio-frontend-prueba.web.app

server:
  error:
    whitelabel:
      enabled: false
  port: ${PORT:8080}

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-z8wk36jr.us.auth0.com/
  web:
    resources:
      add-mappings: false

...