---

application:
  audience: 
  client-origin-url: 

server:
  error:
    whitelabel:
      enabled: false
  port: 

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 
  web:
    resources:
      add-mappings: false

...
